apiVersion: v1
kind: Secret
metadata:
  name: snowalert-secrets
  namespace: default
type: Opaque
data:
  OAUTH_CLIENT_<accountName>: <base64 Encoded Client ID>
  OAUTH_SECRET_<accountName>: <base64 Encoded Client Secret>
  SA_ROLE: <base64 Encoded SA_ROLE>
  SA_DATABASE: <base64 Encoded SA_DATABASE>
  SA_WAREHOUSE: <base64 Encoded SA_WAREHOUSE>
  REGION: <base64 Encoded REGION>
  SNOWFLAKE_ACCOUNT: <base64 Encoded SNOWFLAKE_ACCOUNT>
  PRIVATE_KEY: <base64 Encoded PRIVATE_KEY>
  PRIVATE_KEY_PASSWORD: <base64 Encoded PRIVATE_KEY_PASSWORD>
  JIRA_URL: <base64 Encoded JIRA_URL>
  JIRA_PROJECT: <base64 Encoded JIRA_URL>
  JIRA_USER: <base64 Encoded JIRA_USER>
  JIRA_PASSWORD: <base64 Encoded JIRA_PASSWORD>
